import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Iphone141(),
        ]),
      ),
    );
  }
}

class Iphone141 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 390,
          height: 844,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 390,
                  height: 844,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/390x844"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 109,
                top: 358,
                child: Container(
                  width: 100,
                  height: 100,
                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                ),
              ),
              Positioned(
                left: 59,
                top: 183,
                child: Container(
                  width: 271,
                  height: 427,
                  decoration: BoxDecoration(color: Color(0x7FD9D9D9)),
                ),
              ),
              Positioned(
                left: 0,
                top: 771,
                child: Container(
                  width: 390,
                  height: 73,
                  decoration: BoxDecoration(color: Color(0xD8A2E284)),
                ),
              ),
              Positioned(
                left: 20,
                top: 706,
                child: Container(
                  width: 346,
                  height: 52,
                  decoration: ShapeDecoration(
                    color: Color(0xFFD9D9D9),
                    shape: RoundedRectangleBorder(side: BorderSide(width: 0.50)),
                  ),
                ),
              ),
              Positioned(
                left: 31,
                top: 779,
                child: Container(
                  width: 57,
                  height: 57,
                  decoration: ShapeDecoration(
                    color: Color(0xFF688352),
                    shape: OvalBorder(),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 171.76,
                top: 792,
                child: SizedBox(
                  width: 43,
                  height: 34,
                  child: Transform(
                    transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(0.04),
                    child: Text(
                      '📗',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 40,
                        fontFamily: 'Inter',
                        fontWeight: FontWeight.w400,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 309,
                top: 789,
                child: SizedBox(
                  width: 44,
                  height: 36,
                  child: Text(
                    '⚙️',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 40,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 39,
                top: 792,
                child: SizedBox(
                  width: 41,
                  height: 36,
                  child: Text(
                    '🤖',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 40,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 320,
                top: 712,
                child: Container(
                  width: 41,
                  height: 40,
                  decoration: ShapeDecoration(
                    color: Color(0xFFD9D9D9),
                    shape: OvalBorder(),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 320,
                top: 712,
                child: SizedBox(
                  width: 41,
                  height: 40,
                  child: Text(
                    '🎙️',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 32,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 130,
                top: 229,
                child: Container(
                  width: 126,
                  height: 99,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 163,
                top: 261,
                child: Container(
                  width: 14,
                  height: 29,
                  decoration: ShapeDecoration(
                    color: Color(0xFFD9D9D9),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 208,
                top: 261,
                child: Container(
                  width: 14,
                  height: 29,
                  decoration: ShapeDecoration(
                    color: Color(0xFFD9D9D9),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 134,
                top: 333,
                child: Container(
                  width: 118,
                  height: 34,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 174,
                top: 339,
                child: Container(
                  width: 41,
                  height: 133,
                  decoration: BoxDecoration(color: Colors.white),
                ),
              ),
              Positioned(
                left: 170,
                top: 384,
                child: Container(
                  width: 52,
                  height: 4,
                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                ),
              ),
              Positioned(
                left: 170,
                top: 402,
                child: Container(
                  width: 52,
                  height: 3,
                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                ),
              ),
              Positioned(
                left: 170,
                top: 422,
                child: Container(
                  width: 52,
                  height: 3,
                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                ),
              ),
              Positioned(
                left: 170,
                top: 439,
                child: Container(
                  width: 52,
                  height: 3,
                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                ),
              ),
              Positioned(
                left: 124.74,
                top: 367,
                child: Transform(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(0.39),
                  child: Container(
                    width: 45,
                    height: 97,
                    decoration: ShapeDecoration(
                      color: Colors.white,
                      shape: OvalBorder(),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 226,
                top: 388.49,
                child: Transform(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-0.50),
                  child: Container(
                    width: 42.66,
                    height: 97,
                    decoration: ShapeDecoration(
                      color: Colors.white,
                      shape: OvalBorder(),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 157,
                top: 483,
                child: Container(
                  width: 77,
                  height: 8,
                  decoration: BoxDecoration(color: Colors.white),
                ),
              ),
              Positioned(
                left: 154,
                top: 512,
                child: Container(
                  width: 85,
                  height: 8,
                  decoration: BoxDecoration(color: Colors.white),
                ),
              ),
              Positioned(
                left: 142,
                top: 537,
                child: Container(
                  width: 108,
                  height: 11,
                  decoration: BoxDecoration(color: Colors.white),
                ),
              ),
              Positioned(
                left: 132,
                top: 566,
                child: Container(
                  width: 136,
                  height: 7,
                  decoration: BoxDecoration(color: Colors.white),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}