// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmlBl9KtIwCsuOi8C1QRNtP967JQLB9B4',
    appId: '1:825227883188:web:0d1774bd3fdf4c9d9a1de1',
    messagingSenderId: '825227883188',
    projectId: 'mind-health-e2360',
    authDomain: 'mind-health-e2360.firebaseapp.com',
    storageBucket: 'mind-health-e2360.appspot.com',
    measurementId: 'G-SRTJ46LBY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBB8v0ywapFkwtRng6zplD9lMcIfQnawc',
    appId: '1:825227883188:android:98cc2a9baeb7b9bb9a1de1',
    messagingSenderId: '825227883188',
    projectId: 'mind-health-e2360',
    storageBucket: 'mind-health-e2360.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCWRu0vA5NFOPubjKRZQJQPPS6r95FrpE',
    appId: '1:825227883188:ios:713d01b875c364ae9a1de1',
    messagingSenderId: '825227883188',
    projectId: 'mind-health-e2360',
    storageBucket: 'mind-health-e2360.appspot.com',
    iosClientId: '825227883188-rc395hes2bo4mff1m1be4fsb4gjc6s6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindHealth.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCWRu0vA5NFOPubjKRZQJQPPS6r95FrpE',
    appId: '1:825227883188:ios:713d01b875c364ae9a1de1',
    messagingSenderId: '825227883188',
    projectId: 'mind-health-e2360',
    storageBucket: 'mind-health-e2360.appspot.com',
    iosClientId: '825227883188-rc395hes2bo4mff1m1be4fsb4gjc6s6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindHealth.RunnerTests',
  );
}


